# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d5db88d62fc1712bc852e1716dc1f54ca411597e5a7987b96377594a9da1d90eae5caa6c37a14139d877faa4b78e5da91504f444c9ba180aec1926639b73c08a

test:
  secret_key_base: 2bfee8261b6c3baa3a88caa197f64ee86d7a0f4c9587b85520aa9278e9b822aaf22251e48ebb8b97ad49a378032c06a595f80356347ac9466691c1b94cad2073

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
